name: Main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Main Process
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.22.0
      GOLANGCI_LINT_VERSION: v1.56.2
      CGO_ENABLED: 0

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Setup GOPATH
        run: go env -w GOPATH=${{ github.workspace }}/go

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          go mod download
          go mod vendor

      - name: Lint and Tests
        run: make

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
        if: github.event_name == 'push'
        continue-on-error: true